Wr/parking orbit3
forcedotcom/salesforcedx-templates pull request #503
Opened 2022-07-21 20:33 UTC by WillieRuemmele

### What does this PR do?
parking-orbit `plugin-templates` and `templates` library 🚀 
ran `sf-install` in each package
added a few types
resolved core3 updates

### What issues does this PR fix or reference?
@W-11445939@

2022-07-22 13:58 UTC, mshanemc requested changes
let's fix the proxy thing while we're here

2022-07-22 13:58 UTC, mshanemc commented on packages/plugin-templates/src/utils/messageUtil.ts
> +      this.messages.getMessage(descriptionKey, tokens) + '\n' + this.getHelpHead(isLightningBundle) + (extra || '')
nice approach, putting messages behind the existing util class

2022-07-22 13:58 UTC, mshanemc commented on packages/templates/package.json
>      "typescript": "^4.3.2",
it's a bit odd to have different versions of TS in the different packages?

2022-07-22 13:58 UTC, mshanemc commented on packages/templates/package.json
>      "@types/mkdirp": "0.5.2",
what needs this?

2022-07-22 13:58 UTC, mshanemc commented on packages/templates/src/service/gitRepoUtils.ts
> -    const infoResponse = await got(
this is not gonna be proxy-friendly!  see https://github.com/salesforcecli/plugin-info/pull/75/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

Anytime we're connecting to something outside of a salesforce org (which should go through jsforce connection) we need to check for proxies.  

[I'm gonna figure out how to make this a linter rule eventually, too]

2022-07-28 17:02 UTC, randi274 reviewed
Phew PR of all formatting changes! Some easy nits to fix, and a few questions. Still need to plug in and play around 🔌

2022-07-28 17:02 UTC, randi274 commented on packages/plugin-templates/src/utils/templateCommand.ts
> +      const apiVersionFromConfig = aggregator.getPropertyValue(TemplateCommand.API_VERSION) as string;
should we use `OrgConfigProperties.ORG_API_VERSION` for consistency here?

2022-07-28 21:41 UTC, WillieRuemmele commented on packages/plugin-templates/command-snapshot.json
> +        "plugin": "@salesforce/plugin-templates",
there've been a few changes to the snapshot in the new major version, we now track which plugin a command belongs to, and any aliases they have. This allows us to ensure no breaking changes at the cli level

2022-07-29 18:32 UTC, randi274 commented
@smithgp I added you as a reviewer on this as a heads-up for the Analytics plugin. Not sure if this might impact y'all, but the big changes are updating the command library, and also the [core v2-v3](https://github.com/forcedotcom/sfdx-core/blob/v3/MIGRATING_V2-V3.md) migration.

2022-08-03 18:56 UTC, randi274 approved these changes
Woo! Great work getting this moved over. QA notes are linked in the Quip tab added to the WI. 

You're the Templates Ninja now @WillieRuemmele 🥷 🌟

2022-08-03 20:09 UTC, mshanemc approved these changes

2022-08-03 21:52 UTC, merged