Sm/fixes
forcedotcom/salesforcedx-templates pull request #543
Opened 2023-02-03 17:17 UTC by mshanemc

### What does this PR do?
interface for TemplateOptions has apiVersion and outputDir as optional.  But SfdxGenerator is typed to make them required, so catch-22.

This moves those to instance props that are defaulted in the ctor.

unrelated:
`shelljs` is only used in some npm script, so it moved to devDeps
I bumped `tar` to help with an error related to node18 https://github.com/isaacs/node-tar/issues/321
### What issues does this PR fix or reference?

2023-02-08 23:41 UTC, randi274 requested changes
QA Complete  ✔️  with VS Code - just a few changes!

With Custom template:
✅ Create apex class

With default template:
✅ Create apex class
✅ Create analytics template
✅ Create apex trigger
✅ Create lightning interface
✅ Create LWC
✅ Create LWC Test
✅ Create Aura cmp
✅ Create Aura app
✅ Create Aura event
✅ Create VF page

Failed:
❌ Create VF cmp -> no API version in the meta-xml
❌ Create Project - no sourceApiVersion in the sfdx-project.json
❌ Create Project w/ Manifest - no version set in the package.xml
^^ all should be solved with adding `this` to the apiversion.

2023-02-08 23:41 UTC, randi274 commented on src/generators/visualforceComponentGenerator.ts
> +    const { template, label, apiversion, componentname } = this.options;
Does apiversion here need to be removed?

2023-02-08 23:41 UTC, randi274 commented on src/generators/visualforceComponentGenerator.ts
>          { vfLabel: label, apiVersion: apiversion }
```suggestion
        { vfLabel: label, apiVersion: this.apiversion }
```

2023-02-08 23:41 UTC, randi274 commented on src/generators/visualforceComponentGenerator.ts
>          { vfLabel: label, apiVersion: apiversion }
I wasn't seeing the VF component version set during testing, and think the `this` is all that's missing

2023-02-08 23:41 UTC, randi274 commented on src/generators/projectGenerator.ts
>        loginurl,
From the line above - does apiversion need to be cut here too?

2023-02-08 23:41 UTC, randi274 commented on src/generators/projectGenerator.ts
>          defaultpackagedir,
I can't comment on the apiversion below, but thinking that should also be `this.apiversion`. Is that what sets the sourceApiVersion? I'm not seeing that set when I create a new project with this template.

2023-02-08 23:41 UTC, randi274 commented on src/generators/projectGenerator.ts
>          { apiversion }
```suggestion
        { this.apiversion }
```

2023-02-08 23:41 UTC, randi274 commented on src/generators/projectGenerator.ts
>          { apiversion }
I'm also not seeing the <version> tag set in the manifest file, I think for ^^ reason

2023-02-09 16:13 UTC, mshanemc commented on src/generators/visualforceComponentGenerator.ts
> +    const { template, label, apiversion, componentname } = this.options;
yep!

2023-02-09 16:48 UTC, randi274 approved these changes
✅ Create VF cmp -> now setting API version in the meta-xml
✅ Create Project - now setting sourceApiVersion
✅ Create Project w/ Manifest - now setting version in the package.xml

2023-02-09 17:25 UTC, merged