feat: remove dependency on yeoman
forcedotcom/salesforcedx-templates pull request #587
Opened 2024-06-19 18:43 UTC by mdonnalley

### What does this PR do?

Removes dependency on yeoman-generator and yeoman-environment

### What issues does this PR fix or reference?
@W-16025380@

2024-06-21 13:26 UTC, mshanemc commented on src/service/templateService.ts
> +async function importGenerator(templateType: TemplateType) {
thank you for not making a Factory !

2024-06-21 13:26 UTC, mshanemc commented on src/service/templateService.ts
> +  const generatorClass =
given this pattern, there should probably be something (could be a UT) that enforces the naming convention and location for the generator classes?

2024-06-21 13:26 UTC, mshanemc commented on src/service/templateService.ts
> +  const generatorClass =
ex: you could iterate TemplateType and check that the corresponding generator exists.

an alternative design could be changing TemplateType to be a Map that connected each TemplateType to its corresponding generator to prevent error.

[making these dx comments because the generator stuff is kinda meant to be contributed by lots of different owners]

2024-06-21 13:26 UTC, mshanemc commented on test/service/templateService.test.ts
> +      assert.calledOnce(streamStub);
if it fails, does that mean it was called 0 or more than once?
I prefer `callCount` over these.  If I expect `1` but it fails, it tells me how many times it was called.

2024-06-21 13:26 UTC, mshanemc commented on src/utils/logger.ts
this is awesome!

2024-06-21 13:26 UTC, mshanemc commented on src/generators/sfGenerator.ts
I understand sfdx=>sf for the CLI's stuff.  This lib is used by CLI, but shared by more of the entire salesforce dx.

this class isn't exported, so it could be less "branded" and more about what it's to be used for in this library.  (ex: baseGenerator because every real generator should extend it)

2024-06-21 13:30 UTC, mshanemc requested changes
our plugin that uses this has pretty great NUT coverage (real fs across OSes, etc).  I'd love to see those tests run for library changes to enable ongoing refactoring and dep maintenance for this lib.

If the lib owners aren't up for that, I'd like to see a run of them (maybe branch of a branch) to verify these changes don't affect output.

2024-06-21 18:11 UTC, mdonnalley commented on src/generators/sfGenerator.ts
> +async function pathExists(path: string): Promise<boolean> {
Just blindly copying fs-extra since that's what yeoman was using. I don't think it's actually necessary so I'll remove it

2024-06-24 13:38 UTC, mshanemc commented
I still see one failing NUT on the plugin when I use this branch and your branch on the plugin (running locally)

1) TemplateCommand
       output
         should log json output when flag is specified:
     AssertionError: expected [ 'foo.cls', 'foo.cls-meta.xml' ] to be empty
      at Context.<anonymous> (file:///Users/shane.mclaughlin/eng/salesforcecli/plugin-templates/test/utils/templateCommand.nut.ts:41:61)
      at processImmediate (node:internal/timers:478:21)

2024-06-24 13:47 UTC, mshanemc commented on test/service/templateService.test.ts
> +    it('should have a generator for each TemplateType', async () => {
cool!

2024-06-24 13:52 UTC, mshanemc commented on package.json
> +    "fs-extra": "^11.2.0",
I don't see why fs-extra is needed.

2024-06-24 17:14 UTC, peternhale commented on src/generators/sfGenerator.ts
> +    const cwd = opts?.cwd ?? process.cwd();
Should be adequate.

2024-06-24 17:16 UTC, peternhale approved these changes

2024-06-24 19:51 UTC, mshanemc approved these changes

2024-06-26 13:58 UTC, merged