chore: make templates bundle-able
forcedotcom/salesforcedx-templates pull request #593
Opened 2024-07-31 23:19 UTC by mingxuanzhangsfdx

### What does this PR do?
This PR removes the friction that blocks templates from bundling.
1. transition the generator imports to static imports.
2. use esbuild to bundle it

### What issues does this PR fix or reference?
@W-15736930@

2024-08-01 05:49 UTC, gbockus-sf commented on scripts/esbuild.config.js
> +  format: 'cjs',
can the cli team consume a cjs module now that they are an esm shop?  Might influence what we publish.

2024-08-01 05:49 UTC, gbockus-sf commented on src/service/templateService.ts
> +    templateOptions: any,
nice

2024-08-01 13:31 UTC, peternhale requested changes

2024-08-01 13:31 UTC, peternhale commented on src/service/templateService.ts
> +import { type CreateOutput, TemplateType } from '../utils/types';
Please move the imports/Generators/map to the generators folder.

2024-08-01 13:31 UTC, peternhale commented on src/service/templateService.ts
>  export async function importGenerator(templateType: TemplateType) {
The contents of this function no longer returns a promise.

2024-08-01 17:53 UTC, mingxuanzhangsfdx commented on scripts/esbuild.config.js
> +  format: 'cjs',
That's a good question. I will have a try.

2024-08-01 18:06 UTC, mingxuanzhangsfdx commented on package.json
> +    "/dist",
If we are going to use bundle to publish the project, I guess we have to change it because bundled artifacts exist in dist folder.

2024-08-01 20:03 UTC, mingxuanzhangsfdx commented on scripts/esbuild.config.js
> +  format: 'cjs',
Since we do not need to bundle the project here. I think we do not need to take care of the issue.

2024-08-06 20:33 UTC, peternhale approved these changes

2024-08-06 20:36 UTC, peternhale commented
QA Notes:

Linked this module to plugin-templates and smoke tested the template commands.

- Commands that only have one template (project)
- Commands that have multiple types (Apex class)
-   Used Default
-   Used named

Smoke tests worked fine.

2024-08-06 20:38 UTC, merged